spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/movies_database
    username: postgres
    password: postgres
